spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/agendamento
spring.datasource.username=kayke
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=secret-key-schedule
jwt-expiration=86400000